name: publish NPM
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          cd ./src
          cd ./components
          cd ./Tree
          npm version patch
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
